[package]
name = "ad9361-embedded"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
description = "Platform agnostic AD9361 RF transceiver driver with blocking and async embedded-hal support"
license = "(MIT OR Apache-2.0) AND BSD-3-Clause"
repository = "https://github.com/ustgt-irs/ad9361-embedded"
keywords = ["ad9361", "sdr", "transceiver", "embedded-hal", "no-std"]
categories = ["embedded", "no-std", "hardware-support"]

[dependencies]
arbitrary-int = "2"
bitbybit = "2"
embedded-hal-async = "1"
embedded-hal = "1"
num = { version = "0.4", default-features = false }
heapless = { version = "0.9" }
thiserror = { version = "2", default-features = false }
defmt = { version = "1", optional = true }
strum = { version = "0.28", default-features = false, features = ["derive"] }
bisync2 = "0.3"
axi-ad9361 = { version = "0.1", optional = true }

[features]
default = ["axi-tune"]
axi-tune = ["dep:axi-ad9361"]
defmt = ["dep:defmt", "arbitrary-int/defmt"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--generate-link-to-definition"]
